[project]
name = 'Blockchain-Based-Educational-Accreditation-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.evaluation-tracking]
path = 'contracts/evaluation-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.institution-verification]
path = 'contracts/institution-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.program-registration]
path = 'contracts/program-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.status-monitoring]
path = 'contracts/status-monitoring.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
